const quotesGoodDay = ['"If I cannot do great things, I can do small things in a great way." —Martin Luther King, Jr.', '"Act as if what you do makes a difference. It does." —William James, American philosopher and psychologist', '"Be the change that you wish to see in the world." —Mahatma Ghandi', '"Don\'t sit down and wait for the opportunities to come. Get up and make them." —Madam C.J. Walker', '"Opportunity is missed by most people because it is dressed in overalls and looks like work." —Thomas Edison', '"The most difficult thing is the decision to act; the rest is merely tenacity." —Amelia Earhart', '"The bad news is time flies. The good news is you\'re the pilot." —Michael Altshuler', '"I can\'t change the direction of the wind, but I can adjust my sails to always reach my destination." —Jimmy Dean', '"You get what you give." —Jennifer Lopez', '"It is often the small steps, not the giant leaps, that bring about the most lasting change." —Queen Elizabeth II', '"If what you have done yesterday still looks big to you, you haven\'t done much today." —Mikhail Gorbachev', '"In the long run, you make your own luck — good, bad, or indifferent." —Loretta Lynn', '"If my mind can conceive it, if my heart can believe it, then I can achieve it." —Muhammad Ali', '"Believe you can and you\'re halfway there." —Theodore Roosevelt', '"Never limit yourself because of others\' limited imagination; never limit others because of your own limited imagination" —Mae Jemison, American engineer', '"Challenges are gifts that force us to search for a new center of gravity. Don\'t fight them. Just find a new way to stand." —Oprah Winfrey', '"It ain\'t about how hard you hit. It\'s about how hard you can get hit and keep moving forward." —Sylvester Stallone as Rocky Balboa', '"Our predecessors overcame many troubles and much suffering, but each time got back up stronger than before." —Shinzo Abe, former Prime Minister of Japan', '"I have learned not to allow rejection to move me." —Cicely Tyson, American actress', '"Just don\'t give up trying to do what you really want to do. Where there is love and inspiration, I don\'t think you can go wrong." —Ella Fitzgerald'];

const quotesBadDay = ['"We must believe that we are gifted for something, and that this thing, at whatever cost, must be attained." —Marie Curie, French physicist and chemist', '"The people who are crazy enough to think they can change the world are the ones who do." —Steve Jobs', '"I scorched the earth with my talent and I let my light shine." André Leon Talley, American fashion journalist', '"Nothing is impossible. The word itself says \'I\'m possible!\'" —Audrey Hepburn', '"Never bend your head. Always hold it high. Look the world straight in the eye." —Helen Keller', '"Never allow a person to tell you no who doesn’t have the power to say yes." —Eleanor Roosevelt', '"It took me quite a long time to develop a voice, and now that I have it, I am not going to be silent." —Madeleine Albright, former U.S. Secretary of State', '"You are never too old to set another goal or to dream a new dream." —C.S. Lewis', '"When you have a dream, you\'ve got to grab it and never let go." —Carol Burnett, American comedian and actress', '"Let us make our future now, and let us make our dreams tomorrow\'s reality." —Malala Yousafzai, Pakistani activist', '"All our dreams can come true — if we have the courage to pursue them." —Walt Disney', '"Go confidently in the direction of your dreams. Live the life you have imagined." —Henry David Thoreau', '"All dreams are within reach. All you have to do is keep moving towards them." —Viola Davis, American actress', '"Dreams don\'t have to just be dreams. You can make it a reality; if you just keep pushing and keep trying, then eventually you\'ll reach your goal." —Naomi Osaka, Japanese tennis player', '"Shoot for the moon. Even if you miss, you\'ll land among the stars." —Norman Vincent Peale, American clergyman', '"There is nothing impossible to they who will try." —Alexander the Great', '"Success is not final, failure is not fatal: it is the courage to continue that counts." —Winston Churchill', '"Champions keep playing until they get it right." —Billie Jean King, American tennis player', '"We will fail when we fail to try." —Rosa Parks', '"A person who never made a mistake never tried anything new." —Albert Einstein']

// console.log(quotesGoodDay.length);
// console.log(quotesBadDay.length);

const arrayLength = quotesGoodDay.length;

const randIndex = () => {
    return Math.floor(Math.random() * arrayLength);
}

console.log(`I hope you are having a great day. Remember: ${quotesGoodDay[randIndex()]}`);
console.log(`If you are struggling always know: ${quotesBadDay[randIndex()]}`)